### ISSUE TITLE
compile

### ISSUE THREAD

**Issue by michelmelo** [Innovate-Technologies/player#7]
hello as I compile be using npm start?

**Comment by meyskens** [comment]
What do you mean exactly?

**Comment by michelmelo** [comment]
wanted to test on my server, in theory build npm should do a version dist.

**Comment by meyskens** [comment]
npm build created a version to use in production. If you want to play arround with the code npm run gives a better local envoirement.

**Comment by michelmelo** [comment]
ok, but when I run the "npm build" does nothing.

**Comment by meyskens** [comment]
Did npm install first?

**Comment by leoetlino** [comment]
`npm build` does not create a production version (and it is used by npm internally). You probably meant `npm run build`.

**Comment by michelmelo** [comment]
yes @meyskens  
I changed this:  "build": " webpack --config webpack.build.js --bail --progress",
that is why:  "build": " webpack",

nd it worked.
